site_name: IHC - UVa

theme:
    name: material
    language: pt
    logo: https://cdn.discordapp.com/attachments/752588141298450563/752604546303524934/uva.png
    favicon: https://www.codepuppet.com/wp-content/uploads/2013/10/uva.png

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/Interacao-Humano-Computador/2020.1-UVaJudge

nav:
    - Sobre: index.md
    - Planejamento do Projeto:
        - Porque UVa?: entrega_1/porque_uva.md
        - Cronograma de atividades: entrega_1/cronograma_atividades.md
        - Processo de Design: entrega_1/processo_design.md
        - Sites avaliados: 
            - UVa Online Judge:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_uva.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_uva.md
            - MangaLivre:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_mangalivre.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_mangalivre.md
            - Poupa Tempo SP:
                - Planejamento da avaliação: entrega_1/planejamentos_individuais/planejamento_poupatemposp.md
                - Avaliação: entrega_1/avaliacoes_individuais/avaliacao_poupatemposp.md
        - Ferramentas: entrega_1/ferramentas.md
    - Análise de requisitos:
        - Análise do Perfil de Usuário:
            - Personas: entrega_2/personas.md
            - Análise de tarefas: entrega_2/analise_tarefas.md
            - Questionário 1: entrega_2/questionario.md
            - Questionário 2: entrega_4/questionario2.md
            - Entrevista: entrega_4/entrevista.md
            - Perfil de usuário: entrega_2/perfil_usuario.md
        - Princípios e diretrizes do projeto: entrega_3/principios_gerais.md
        - Características da Plataforma: entrega_3/caracteristicas_plataforma.md
        - Metas de Usabilidade: entrega_3/metas_usabilidade.md
        - Guia de estilo: entrega_3/guia_estilo.md
    - Design, avaliação e desenvolvimento:
        - Nível 1:
            - Storyboard: entrega_4/storyboard.md
            - Planejamento da Avaliação: entrega_4/planejamento_avaliacao.md
            - Planejamento do Teste Piloto: entrega_4/planejamento_teste_piloto.md
            - Avaliação e Relato dos Resultados:
                - Storyboard: entrega_5/avaliacao/storyboard.md
                - Análise de Tarefas: entrega_5/avaliacao/analise_tarefas.md
        - Nível 2:
            - Protótipo de Papel:
                - Protótipo de Papel de Baixa Fidelidade: entrega_5/prototipo_papel/prototipo.md
                - Planejamento da Avaliação: entrega_5/prototipo_papel/planejamento_avaliacao.md
                - Avaliação e Relato dos Resultados: entrega_6/prototipo_papel/avaliacao_relato.md
        - Nível 3:
            - Protótipo Final:
                - Protótipo de Alta Fidelidade: entrega_6/prototipo_alta/prototipo.md
                - Planejamento da Avaliação: entrega_6/prototipo_alta/planejamento_avaliacao.md
                - Avaliação e Relato dos Resultados: entrega_6/prototipo_alta/avaliacao_relato.md
            - Teste Piloto: entrega_6/teste_piloto.md
            - Teste de Usabilidade:
                - Planejamento da Avaliação: entrega_7/teste_de_usabilidade/planejamento.md
                - Thiago: entrega_7/teste_de_usabilidade/thiago.md
                - Patrick: entrega_7/teste_de_usabilidade/patrick.md
                - Eduarda: entrega_7/teste_de_usabilidade/eduarda.md
                - Relato dos Resultados: entrega_7/teste_de_usabilidade/relato.md
    - Atas das reuniões:
        - Reunião 1: atas/reuniao_1.md
        - Reunião 2: atas/reuniao_2.md
        - Reunião 3: atas/reuniao_3.md
        - Reunião 4: atas/reuniao_4.md
        - Reunião 5: atas/reuniao_5.md
        - Reunião 6: atas/reuniao_6.md
        - Reunião 7: atas/reuniao_7.md
        - Reunião 8: atas/reuniao_8.md
        - Reunião 9: atas/reuniao_9.md
        - Reunião 10: atas/reuniao_10.md
        - Reunião 11: atas/reuniao_11.md
        - Reunião 12: atas/reuniao_12.md
        - Reunião 13: atas/reuniao_13.md
        - Reunião 14: atas/reuniao_14.md
        - Reunião 15: atas/reuniao_15.md
    - Apresentações:
        - Apresentação 1: apresentacoes/apresentacao_1.md
        - Apresentação 2: apresentacoes/apresentacao_2.md
        - Apresentação 3: apresentacoes/apresentacao_3.md
        - Apresentação 4: apresentacoes/apresentacao_4.md
        - Apresentação 5: apresentacoes/apresentacao_5.md
        - Apresentação 6: apresentacoes/apresentacao_6.md
        - Apresentação 7: apresentacoes/apresentacao_7.md
